/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_mobile_analytics_app_id: "1bcb5563048740be86ea583712f18de5",
  aws_mobile_analytics_app_region: "us-east-1",
  Analytics: {
    AWSPinpoint: {
      appId: "1bcb5563048740be86ea583712f18de5",
      region: "us-east-1",
    },
  },
  Notifications: {
    Push: {
      AWSPinpoint: {
        appId: "1bcb5563048740be86ea583712f18de5",
        region: "us-east-1",
      },
    },
  },
  aws_cloud_logic_custom: [
    {
      name: "upWagmiUserApi",
      endpoint:
        "https://dj56p3u1qe.execute-api.us-east-1.amazonaws.com/upwagmitec",
      region: "us-east-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "us-east-1:3ac931ac-c305-46a1-9ef1-f9e9ead1ad2d",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_tTejiiLwi",
  aws_user_pools_web_client_id: "44id390v77t1qvgc0hm5j9t1b2",
  oauth: {
    domain:
      "upwagmidev3462d23d-3462d23d-upwagmitec.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn:
      "io.upschool.upapp://callback/,io.upschool.upapp://callback/",
    redirectSignOut: "io.upschool.upapp://signout/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: ["GOOGLE"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_dynamodb_all_tables_region: "us-east-1",
  aws_dynamodb_table_schemas: [
    {
      tableName: "UpConversationMessage-upwagmitec",
      region: "us-east-1",
    },
    {
      tableName: "UpConversations-upwagmitec",
      region: "us-east-1",
    },
    {
      tableName: "User-upwagmitec",
      region: "us-east-1",
    },
    {
      tableName: "Badges-upwagmitec",
      region: "us-east-1",
    },
  ],
  aws_user_files_s3_bucket: "upwagmidevcontent234355-upwagmitec",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;
