/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_mobile_analytics_app_id": "55341b7171614f8cb0043719479a7e52",
    "aws_mobile_analytics_app_region": "us-east-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "55341b7171614f8cb0043719479a7e52",
            "region": "us-east-1"
        }
    },
    "Notifications": {
        "Push": {
            "AWSPinpoint": {
                "appId": "55341b7171614f8cb0043719479a7e52",
                "region": "us-east-1"
            }
        }
    },
    "aws_cloud_logic_custom": [
        {
            "name": "upWagmiUserApi",
            "endpoint": "https://ixoy0ncts9.execute-api.us-east-1.amazonaws.com/myenv",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:1a6f71e1-a993-4a11-85cc-800577e409f2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_akkBktCUt",
    "aws_user_pools_web_client_id": "a5ulkgpppnij4cmhtohg0krrs",
    "oauth": {
        "domain": "upwagmidev4016790c-4016790c-myenv.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "io.upschool.upapp://callback/",
        "redirectSignOut": "io.upschool.upapp://signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "AccountabilityPartners-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "AccountabilityPartnersProgress-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "AssistantGroup-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "Badges-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "ConsumedToken-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "ContextScope-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "ContextScopeType-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "ConversationQuestions-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "ConversationRecaps-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "ElectionOptions-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "Notifications-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "Path-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "PathPopUp-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "PromoCode-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "PromoCodeUserMapping-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "QuestionPool-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "SubscriptionRequests-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UpAssistant-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "User-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UserGroup-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UserGroupAssistants-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UserGroupRequest-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UserNotificationSchedule-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UserSessions-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UserSubscriptions-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "analysisResults-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UpConversationMessage-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "UpConversations-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "realtimeCache-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "spaceRepetitionAssistants-myenv",
            "region": "us-east-1"
        },
        {
            "tableName": "userProfile-myenv",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "upwagmidevcontentc4a48-myenv",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
